name: Deploy Web Application

on:
  push:
    branches: [ "main", "Clean-up-+-standard-+-secrets" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Inject Environment Variables and Secrets
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DEFAULT_BOT_NAME: ${{ vars.DEFAULT_BOT_NAME }}
        run: |
          sed -i "s|DISCORD_WEBHOOK_PLACEHOLDER|${DISCORD_WEBHOOK_URL}|g" js/app.js
          sed -i "s|DEFAULT_BOT_NAME_PLACEHOLDER|${DEFAULT_BOT_NAME}|g" js/app.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./